### ISSUE TITLE
Suggestion: only show latest chapter in "Latest Additions"

### ISSUE THREAD

**Issue by abulgatz** [Amit-P-Amin/RationalReads#1]
Currently, the "Latest Additions" section on the front page is clogged up with many chapters from the same story. For example, Metropolitan Man currently takes up half the list on the front page with chapters 8-13. To make the list more useful, I think each story should only get one entry in the section, or there should be a toggle to choose which mode to display (by chapter or by story).

**Comment by Amit-P-Amin** [comment]
That's an excellent idea Adam, thank you! I'll go ahead and add that to the feature list.
