### ISSUE TITLE
New lines destroyed or not displayed for comments.

### ISSUE THREAD

**Issue by Amit-P-Amin** [Amit-P-Amin/RationalReads#8]
I just posted a couple more reviews and on each of them all formatting was lost after the post. This condensed several paragraphs of comments into a single unreadable block of text. I have not had that problem before so I am not sure what is causing, but thought I should point out.

**Comment by nevinera** [comment]
It looks like your `comment_show` [template](https://github.com/Amit-P-Amin/RationalReads/blob/master/app/assets/templates/comments/comment_show.jst.ejs) just puts the comments in a div - raw text in html ignores whitespace (if you run `gsub(/\s+/, ' ')` on it, you render the same result). The easy answer is to style a `pre` tag so it doesn't look awful, or to split on newlines and wrap individual paragraphs in `p` tags.

Would you prefer markdown, like reddit? I've added that to a few of my projects, it's pretty easy to manage with `redcarpet`.

**Comment by Amit-P-Amin** [comment]
Awesome! That was easy to fix! Do you think markdown would be helpful? I can't imagine it getting used that often.

**Comment by nevinera** [comment]
Yeah, probably not that important, since it's not really a discussion site.
